var directiveshtml = [
    {
        directive: "CSRD",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">Corporate Sustainability Reporting Directive</div><div class="rR-QuickInfo"><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>2</p><div class="tooltip">2 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>05.01.2023</p><div class="tooltip">Deadline: 05.01.2023</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.png" alt=""><div class="tooltip">High risk</div></div></div><p class="rR-text">The Corporate Sustainability Reporting Directive (CSRD) is a proposed EU legislation that aims to enhance corporatesustainability reporting and disclosure requirements. It builds on the existing Non-Financial Reporting Directive (NFRD)and expands its scope to include more companies, introduce mandatory sustainability reporting standards, and improve thequality and comparability of reported information.</p></div>'
    },
    {
        directive: "Corporate Sustainability Due Diligence Directive",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">Corporate Sustainability Due Diligence Directive</div><div class="rR-QuickInfo"><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>1</p><div class="tooltip">1 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>01.06.2023</p><div class="tooltip">Deadline: 01.06.2023</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.png" alt=""><div class="tooltip">High risk</div></div></div><p class="rR-text">The Corporate Sustainability Due Diligence Directive is a proposed EU legislation that aims to require companies to conduct due diligence on their supply chains and prevent human rights abuses, environmental damage, and other adverse impacts. The directive builds on existing international standards and guidelines, such as the UN Guiding Principles on Business and Human Rights.</p></div>'
    },
    {
        directive: "European Sustainability Reporting Standards",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">European Sustainability Reporting Standards</div><div class="rR-QuickInfo"><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>1</p><div class="tooltip">1 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>06.2023</p><div class="tooltip">Deadline: 06.2023</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.black.png" alt="" class="imgvellow"><div class="tooltip">Medium risk</div></div></div><p class="rR-text">The European Sustainability Reporting Standards (ESRS) directive is a proposed regulation by the European Commission aimed at establishing a common set of sustainability reporting standards for companies operating in the EU. The directive aims to enhance transparency and comparability of sustainability information disclosed by companies, enabling investors and stakeholders to make informed decisions. It builds upon existing reporting frameworks and standards, such as the Global Reporting Initiative (GRI) and the Task Force on Climate-related Financial Disclosures (TCFD).</p></div>'
    },
    {
        directive: "Supply Chain Act",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">Supply Chain Act</div><div class="rR-QuickInfo"><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>1</p><div class="tooltip">1 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>01.01.2023</p><div class="tooltip">Deadline: 01.01.2023</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.black.png" alt="" class="imgred"><div class="tooltip">high risk</div></div></div><p class="rR-text">The Supply Chain Act directive is a proposed legislation aimed at addressing human rights and environmental issues in global supply chains. It is a response to concerns about forced labor, child labor, deforestation, and other sustainability issues in supply chains. The directive seeks to hold companies accountable for their supply chain practices and ensure that they respect human rights and environmental standards.</p></div>'
    },
    {
        directive: "EU Taxonomy",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">EU Taxonomy</div><div class="rR-QuickInfo"><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>3</p><div class="tooltip">3 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>2024</p><div class="tooltip">Deadline: 2024</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.black.png" alt="" class="imgred"><div class="tooltip">high risk</div></div></div><p class="rR-text">The EU Taxonomy Regulation was adopted in June 2020 as part of the European Green Deal. Its main objective is to establish a classification system for sustainable economic activities, providing a common language for investors and companies to identify environmentally sustainable investments. The taxonomy sets out criteria for determining whether an economic activity can be considered environmentally sustainable.</p></div>'
    },
    {
        directive: "EU Taxonomy Future",
        html: '<div class="rRegu"><!-- <div class="rR-implemented"><img src="/IMG/checkmark.shield.png" alt=""><p>implemented</p></div> --><div class="rR-Head">EU Taxonomy</div><div class="rR-QuickInfo"><div class="rRQ-element rRQ-Info"><img src="/IMG/warning.yellow.png" alt=""><div class="tooltip">Relevant in the future</div></div><div class="rRQ-element"><img src="/IMG/arrow.2.squarepath.png" alt=""><p>3</p><div class="tooltip">3 Updates</div></div><div class="rRQ-element rQE-deadline"><img src="/IMG/calendar.badge.clock.png" alt=""><p>2024</p><div class="tooltip">Deadline: 2024</div></div><div class="rRQ-element rRQE-risk"><img src="/IMG/exclamationmark.triangle.black.png" alt="" class="imgred"><div class="tooltip">high risk</div></div></div><p class="rR-text">The EU Taxonomy Regulation was adopted in June 2020 as part of the European Green Deal. Its main objective is to establish a classification system for sustainable economic activities, providing a common language for investors and companies to identify environmentally sustainable investments. The taxonomy sets out criteria for determining whether an economic activity can be considered environmentally sustainable.</p></div>'
    },
]

for (let el of directiveshtml) {
    document.getElementsByClassName('mMainContent')[0].innerHTML += el.html;
}